---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: tushpatt/rollout:blue
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
  strategy:
    blueGreen:
      activeService: demoapp-blue
      previewService: demoapp-green
      prePromotionAnalysis:
        templates:
        - templateName: realtime-analysis
        args:
        - name: service-name
          value: demoapp-preview.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-blue
  labels:
    app: demoapp
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demoapp
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-green
  labels:
    app: demoapp
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demoapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demoapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /greet
        backend:
          serviceName: demoapp-blue
          servicePort: 80
